-- Создаём таблицу настроек чата
CREATE TABLE IF NOT EXISTS public.chats (
  id          bigint generated by default as identity primary key,
  chat_id     bigint not null unique,
  link_filter_enabled boolean not null default true,  -- true = ссылки запрещены
  created_at  timestamp with time zone default timezone('utc', now()) not null,
  updated_at  timestamp with time zone default timezone('utc', now()) not null
);

-- Включаем RLS
ALTER TABLE public.chats ENABLE ROW LEVEL SECURITY;

-- Политика (разрешаем всё для сервисного ключа)
CREATE POLICY "Enable all for service role" ON public.chats
  FOR ALL USING (true) WITH CHECK (true);

-- Индекс для быстрого поиска по chat_id
CREATE INDEX IF NOT EXISTS chats_chat_id_idx ON public.chats (chat_id);
