-- Таблица пользователей (статистика)
create table users (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  user_id bigint not null,
  username text,
  first_name text,
  xp int default 0,
  level int default 1,
  reputation int default 0,
  warns int default 0,
  last_message_time bigint default 0,
  unique(chat_id, user_id)
);

-- Таблица запрещенных слов
create table bad_words (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  word text not null
);

-- Включаем RLS (безопасность), но для сервисного ключа это не обязательно
alter table users enable row level security;
alter table bad_words enable row level security;

-- Политики (разрешаем все для простоты, так как используем сервисный ключ)
create policy "Enable all for service role" on users for all using (true);
create policy "Enable all for service role" on bad_words for all using (true);
