create table if not exists public.bot_persona_state (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    user_id bigint not null,
    troll double precision not null default 0.42,
    warmth double precision not null default 0.58,
    chaos double precision not null default 0.30,
    attachment double precision not null default 0.18,
    respect double precision not null default 0.50,
    stage text not null default 'fresh',
    exchanges integer not null default 0,
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.bot_persona_state
    add column if not exists troll double precision not null default 0.42;
alter table public.bot_persona_state
    add column if not exists warmth double precision not null default 0.58;
alter table public.bot_persona_state
    add column if not exists chaos double precision not null default 0.30;
alter table public.bot_persona_state
    add column if not exists attachment double precision not null default 0.18;
alter table public.bot_persona_state
    add column if not exists respect double precision not null default 0.50;
alter table public.bot_persona_state
    add column if not exists stage text not null default 'fresh';
alter table public.bot_persona_state
    add column if not exists exchanges integer not null default 0;
alter table public.bot_persona_state
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists bot_persona_state_chat_user_uidx
    on public.bot_persona_state (chat_id, user_id);
