create table if not exists public.bot_knowledge (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    fact text not null,
    fact_type text not null default 'memory_fact',
    confidence double precision not null default 0.7,
    status text not null default 'confirmed',
    meta jsonb not null default '{}'::jsonb,
    entity_user_id bigint,
    entity_name text,
    source_message_id bigint,
    created_at timestamptz not null default timezone('utc', now()),
    last_seen_at timestamptz not null default timezone('utc', now())
);

alter table public.bot_knowledge
    add column if not exists fact_type text not null default 'memory_fact',
    add column if not exists confidence double precision not null default 0.7,
    add column if not exists status text not null default 'confirmed',
    add column if not exists meta jsonb not null default '{}'::jsonb,
    add column if not exists entity_user_id bigint,
    add column if not exists entity_name text,
    add column if not exists source_message_id bigint,
    add column if not exists created_at timestamptz not null default timezone('utc', now()),
    add column if not exists last_seen_at timestamptz not null default timezone('utc', now());

update public.bot_knowledge
set entity_user_id = (meta->>'user_id')::bigint
where entity_user_id is null
  and meta ? 'user_id'
  and (meta->>'user_id') ~ '^-?[0-9]+$';

update public.bot_knowledge
set entity_name = coalesce(nullif(meta->>'user_name', ''), nullif(meta->>'entity_name', ''))
where entity_name is null
  and (meta ? 'user_name' or meta ? 'entity_name');

update public.bot_knowledge
set source_message_id = (meta->>'source_message_id')::bigint
where source_message_id is null
  and meta ? 'source_message_id'
  and (meta->>'source_message_id') ~ '^-?[0-9]+$';

create index if not exists bot_knowledge_chat_status_seen_idx
    on public.bot_knowledge (chat_id, status, last_seen_at desc);

create index if not exists bot_knowledge_entity_user_idx
    on public.bot_knowledge (chat_id, entity_user_id, status, last_seen_at desc);

create index if not exists bot_knowledge_source_message_idx
    on public.bot_knowledge (chat_id, source_message_id);
