create table if not exists public.message_logs (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    message_id bigint not null,
    user_id bigint not null,
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists message_logs_chat_message_uidx
    on public.message_logs (chat_id, message_id);

create index if not exists message_logs_lookup_idx
    on public.message_logs (chat_id, message_id);
