-- Создаем таблицу для хранения истории сообщений (кто какое сообщение написал)
create table public.message_logs (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  message_id bigint not null,
  user_id bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Создаем индекс для быстрого поиска по чату и ID сообщения
create index message_logs_lookup_idx on public.message_logs (chat_id, message_id);

-- Политика безопасности (разрешаем всё для сервисного ключа)
alter table public.message_logs enable row level security;
create policy "Enable all for service role" on public.message_logs using (true) with check (true);
